#!/bin/sh

for s in work main projects monitoring; do tmux has-session -t "$s" 2>/dev/null || tmux new-session -d -s "$s"; done; tmux has-session -t chat 2>/dev/null || tmux new-session -d -s chat 'weechat'; tmux attach -t main
